dev:
  build: .
  ports:
    - "8080:80"
  volumes:
    - .:/var/www
  links:
    - phantomjs

phantomjs:
  image: cmfatih/phantomjs 
  ports:
    - 8643
  entrypoint: phantomjs
  command: "--webdriver=8643"
